// The server build file is generated by `remix vite:build`
import * as server from '../build/server/index.js';

export const onRequest = async (request: Request) => {
  const { default: handleRequest } = server as any;

  if (typeof handleRequest !== 'function') {
    return new Response("Server build doesn't export a handleRequest function", { status: 500 });
  }

  return handleRequest(
    request,
    200,
    new Headers(),
    { loaderData: {}, actionData: {}, matches: [], errors: null }
  );
};
